spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/simpleapp
    username: root
    password: rootpass
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
